Update single_test.yml

diff --git a/.github/workflows/single_test.yml b/.github/workflows/single_test.yml
--- a/.github/workflows/single_test.yml
+++ b/.github/workflows/single_test.yml
@@ -32,7 +32,7 @@ jobs:
         include:
           - version: 7.2 
             platform: geminilake
-            parm: 'prod-v7'
+            parm: 'dev-v7'
 
     runs-on: ubuntu-latest
 
@@ -46,17 +46,99 @@ jobs:
           git config --global user.name "github-actions[bot]"
           sudo timedatectl set-timezone "Asia/Seoul"
           
-      - name: Make lkms
+      - name: Get EnvDeploy
         run: |
           ROOT_PATH=${{ github.workspace }}
-          VERSION=${{ matrix.version }}
-          PLATFORM=${{ matrix.platform }}
-          . ${ROOT_PATH}/compile.sh
-          echo "makeEnvDeploy"
-          makeEnvDeploy "${ROOT_PATH}" "${VERSION}" "${PLATFORM}"
-          echo "makemodules"
-          makelkms "${ROOT_PATH}" "${VERSION}" "${PLATFORM}" "${ROOT_PATH}" "${ROOT_PATH}/output"
-          
+
+          git clone https://github.com/SynologyOpenSource/pkgscripts-ng.git ${ROOT_PATH}/pkgscripts-ng
+          cd ${ROOT_PATH}/pkgscripts-ng
+          # if version == 6.2, checkout 6.2.4
+          git checkout DSM${{ matrix.version }}`[ "${{ matrix.version }}" = "6.2" ] && echo ".4"`
+          sudo ./EnvDeploy -v ${{ matrix.version }}`[ "${{ matrix.version }}" = "6.2" ] && echo ".4"` -l  # Get Available platforms
+          sudo ./EnvDeploy -q -v ${{ matrix.version }} -p ${{ matrix.platform }}
+
+          # Fault tolerance of pkgscripts-ng
+          if [[ "${{ matrix.platform }}" == "broadwellntbap" && "${{ matrix.version }}" == "7.1" ]]; then
+            sed -i '/		broadwellnk	BROADWELLNK/a\		broadwellntbap  BROADWELLNTBAP                  linux-4.4.x             Intel Broadwell with ntb kernel config in AP mode' ${ROOT_PATH}/pkgscripts-ng/include/platforms
+          fi
+
+          #ENV
+          mkdir -p ${ROOT_PATH}/source
+
+          ENV_PATH=${ROOT_PATH}/build_env/ds.${{ matrix.platform }}-${{ matrix.version }}
+          sudo cp -al ${ROOT_PATH}/pkgscripts-ng ${ENV_PATH}/
+
+          sudo chroot ${ENV_PATH} << "EOF"
+          cd pkgscripts
+
+          version=${{ matrix.version }}; [ ${version:0:1} -gt 6 ] && sed -i 's/print(" ".join(kernels))/pass #&/' ProjectDepends.py
+          sed -i '/PLATFORM_FAMILY/a\\techo "PRODUCT=$PRODUCT" >> $file\n\techo "KSRC=$KERNEL_SEARCH_PATH" >> $file\n\techo "LINUX_SRC=$KERNEL_SEARCH_PATH" >> $file' include/build
+          ./SynoBuild -c -p ${{ matrix.platform }}
+
+          while read -r line; do if [ ${line:0:1} != "#" ]; then export ${line%%=*}="${line#*=}"; fi; done < /env${BUILD_ARCH}.mak
+          if [ -f "${KSRC}/Makefile" ]; then
+            # gcc issue "unrecognized command-line option '--param=allow-store-data-races=0'".
+            [ "${{ matrix.version }}" == "7.2" ] && sed -i 's/--param=allow-store-data-races=0/--allow-store-data-races/g' ${KSRC}/Makefile
+
+            VERSION=`cat ${KSRC}/Makefile | grep ^VERSION | awk -F' ' '{print $3}'`
+            PATCHLEVEL=`cat ${KSRC}/Makefile | grep ^PATCHLEVEL | awk -F' ' '{print $3}'`
+            SUBLEVEL=`cat ${KSRC}/Makefile | grep ^SUBLEVEL | awk -F' ' '{print $3}'`
+            [ -f "/env32.mak" ] && echo "KVER=${VERSION}.${PATCHLEVEL}.${SUBLEVEL}" >> /env32.mak
+            [ -f "/env64.mak" ] && echo "KVER=${VERSION}.${PATCHLEVEL}.${SUBLEVEL}" >> /env64.mak
+            CCVER=`$CC --version | head -n 1 | awk -F' ' '{print $3}'`
+            [ -f "/env32.mak" ] && echo "CCVER=${CCVER}" >> /env32.mak
+            [ -f "/env64.mak" ] && echo "CCVER=${CCVER}" >> /env64.mak
+          fi
+          EOF
+
+          [ -f ${ENV_PATH}/env64.mak ] && ENV_FILE=${ENV_PATH}/env64.mak || ([ -f ${ENV_PATH}/env32.mak ] && ENV_FILE=${ENV_PATH}/env32.mak)
+          if [ -n "${ENV_FILE}" ]; then
+            KVER=`grep 'KVER=' ${ENV_FILE} | awk -F'=' '{print $2}'`
+            CCVER=`grep 'CCVER=' ${ENV_FILE} | awk -F'=' '{print $2}'`
+            [ -n "${KVER}" ] && echo "KVER=${KVER}" >> $GITHUB_ENV
+            [ -n "${CCVER}" ] && echo "CCVER=${CCVER}" >> $GITHUB_ENV
+          fi
+
+      - name: Make LKMs
+        run: |
+          sudo chroot build_env/ds.${{ matrix.platform }}-${{ matrix.version }} << "EOF"
+          sed -i 's/^CFLAGS=/#CFLAGS=/g; s/^CXXFLAGS=/#CXXFLAGS=/g' /env${BUILD_ARCH}.mak
+          while read -r line; do if [ ${line:0:1} != "#" ]; then export ${line%%=*}="${line#*=}"; fi; done < /env${BUILD_ARCH}.mak
+          mkdir -p /source/output
+
+          repo=${{ github.server_url }}/${{ github.repository }}
+          # 5.10.55 Temporary use of https://github.com/XPEnology-Community/redpill-lkm5
+          # And currently only USB OK, @jim3ma is adapting to 7.2.
+          [ "${KVER:0:1}" = "5" ] && repo=https://github.com/AuxXxilium/redpill-lkm5
+
+          git clone -c http.sslVerify=false ${repo} /source/input
+          cd /source/input
+          [ -z "`grep 'env.mak' Makefile`" ] && sed -i '1 i include /env.mak' Makefile
+          array=(${{ matrix.parm }})
+          for a in ${array[@]}
+          do
+            make ${a}
+            if [ -f redpill.ko ]; then
+              strip -g redpill.ko    # Discard symbols from object files. 
+              RPKOVER=$(modinfo --field=vermagic redpill.ko | awk '{print $1}')
+              gzip redpill.ko
+              if [ "${{ matrix.platform }}" = "epyc7002" ]; then
+                mv -f ./redpill.ko.gz /source/output/rp-${{ matrix.platform }}-${{ matrix.version }}-${RPKOVER/+/}-`echo ${a} | awk -F'-' '{print $1}'`.ko.gz
+              else
+                mv -f ./redpill.ko.gz /source/output/rp-${{ matrix.platform }}-${RPKOVER/+/}-`echo ${a} | awk -F'-' '{print $1}'`.ko.gz
+              fi
+            else
+              echo "error"
+            fi
+            make clean
+          done        
+          ls -al /source/output
+          EOF
+
+          ROOT_PATH=${{ github.workspace }}
+          mkdir -p ${ROOT_PATH}/source
+          sudo cp -a ${ROOT_PATH}/build_env/ds.${{ matrix.platform }}-${{ matrix.version }}/source/output ${ROOT_PATH}/source/
+
       - name: Upload to Artifacts
         uses: actions/upload-artifact@v3
         with:
@@ -68,6 +150,7 @@ jobs:
         # if: ${{ steps.cache-env.outputs.cache-hit == 'true' }}
         run: |
           sudo rm -rf ${{ github.workspace }}/build_env/ds.${{ matrix.platform }}-${{ matrix.version }}/source/*
+
 
   release:
     runs-on: ubuntu-latest
